name = input("Enter your name: ")
surname = input("Enter your surname: ")
age = input("enter your age: ")
number1 = input("enter number1: ")
number2 = input("enter number2: ")
print(name)
print(surname)
print(age)
print(number1)
print(number2)

num1 = input("enter number1: 80 ")
num2 = input("enter number2: 100")
print(num1 + num2)



name = input("Enter your name: ")
surname = input("Enter your surname: ")
age = input("enter your age: ")
number1 = input("enter number1: ")
number2 = input("enter number2: ")
print(type(name))
print(type(surname))
print(type(age))
print(type(number1))
print(type(number2))